// maybe_need/ COGNITIVE ORCHESTRATION-ISO22301/BCM-v1/frontend/18:09/web_portal_enhanced_current_2259_OLD/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <!-- Dashboard Header -->
    <div class="dashboard-header">
      <div>
        <h1 class="dashboard-title">BCM Dashboard</h1>
        <p class="dashboard-subtitle">Business Continuity Management Overview</p>
      </div>
      <div class="header-actions">
        <button @click="refresh" class="refresh-button" :disabled="isLoading">
          <ArrowPathIcon class="w-4 h-4" :class="{ 'animate-spin': isLoading }" />
          Refresh
        </button>
      </div>
    </div>

    <!-- KPI Overview -->
    <div class="kpi-grid">
      <div v-for="kpi in kpiData" :key="kpi.id" class="kpi-card">
        <div class="kpi-header">
          <component :is="kpi.icon" class="kpi-icon" :class="kpi.iconColor" />
          <span class="kpi-trend" :class="kpi.trend">
            <ArrowUpIcon v-if="kpi.trend === 'up'" class="w-3 h-3" />
            <ArrowDownIcon v-if="kpi.trend === 'down'" class="w-3 h-3" />
          </span>
        </div>
        <div class="kpi-value">{{ kpi.value }}</div>
        <div class="kpi-label">{{ kpi.label }}</div>
        <div class="kpi-change" :class="kpi.changeType">
          {{ kpi.change }}
        </div>
      </div>
    </div>

    <!-- Main Content Grid -->
    <div class="content-grid">
      <!-- System Health -->
      <div class="dashboard-card">
        <div class="card-header">
          <h3 class="card-title">System Health</h3>
          <span class="health-status" :class="healthStatus.level">
            {{ healthStatus.label }}
          </span>
        </div>
        <div class="health-overview">
          <div class="health-circle" :class="healthStatus.level">
            <div class="health-percentage">{{ healthStatus.percentage }}%</div>
          </div>
        </div>
        <div class="health-status-text">{{ healthStatus.description }}</div>
        <div class="health-details">
          <div v-for="item in healthDetails" :key="item.name" class="health-item">
            <div class="flex items-center gap-2">
              <div class="health-indicator" :class="{ 'healthy': item.status === 'healthy' }"></div>
              <span class="text-sm text-slate-900 dark:text-white">{{ item.name }}</span>
            </div>
            <span class="health-value">{{ item.value }}</span>
          </div>
        </div>
      </div>

      <!-- Quick Actions -->
      <div class="dashboard-card">
        <div class="card-header">
          <h3 class="card-title">Quick Actions</h3>
        </div>
        <div class="quick-actions-grid">
          <button
            v-for="action in quickActions"
            :key="action.id"
            @click="executeAction(action.id)"
            class="quick-action-button"
          >
            <component :is="action.icon" class="action-icon" />
            <span class="action-title">{{ action.title }}</span>
            <span class="action-description">{{ action.description }}</span>
          </button>
        </div>
      </div>

      <!-- Recent Activity -->
      <div class="dashboard-card">
        <div class="card-header">
          <h3 class="card-title">Recent Activity</h3>
          <div class="activity-controls">
            <div class="activity-filters">
              <button
                v-for="filter in activityFilters"
                :key="filter"
                @click="activeFilter = filter"
                class="filter-button"
                :class="{ 'active': activeFilter === filter }"
              >
                {{ filter }}
              </button>
            </div>
            <div class="activity-live-indicator" :class="{ 'active': isLiveUpdates }">
              <div class="live-dot"></div>
              Live
            </div>
          </div>
        </div>
        <div class="activity-list">
          <div
            v-for="activity in filteredActivities"
            :key="activity.id"
            class="activity-item"
            @click="viewActivity(activity.id)"
          >
            <div class="activity-icon" :class="`activity-${activity.type}`">
              <component :is="activity.icon" class="w-4 h-4" />
            </div>
            <div class="activity-content">
              <div class="activity-header">
                <h4 class="activity-title">{{ activity.title }}</h4>
                <span class="activity-severity" :class="activity.severity">
                  {{ activity.severity }}
                </span>
              </div>
              <p class="activity-description">{{ activity.description }}</p>
              <div class="activity-meta">
                <span class="activity-user">{{ activity.user }}</span>
                <span>{{ formatTime(activity.timestamp) }}</span>
                <span>{{ activity.module }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Risk Overview -->
      <div class="dashboard-card">
        <div class="card-header">
          <h3 class="card-title">Risk Overview</h3>
        </div>
        <div class="risk-container">
          <div class="risk-chart">
            <!-- Chart will be rendered here -->
            <canvas ref="riskChart"></canvas>
          </div>
          <div class="risk-summary">
            <div class="risk-item high">
              <div class="risk-indicator"></div>
              <span>{{ riskData.high }} High</span>
            </div>
            <div class="risk-item medium">
              <div class="risk-indicator"></div>
              <span>{{ riskData.medium }} Medium</span>
            </div>
            <div class="risk-item low">
              <div class="risk-indicator"></div>
              <span>{{ riskData.low }} Low</span>
            </div>
          </div>
          <div class="risk-actions">
            <Button size="sm" variant="secondary" @click="viewRisks">
              View All Risks
            </Button>
            <Button size="sm" variant="primary" @click="createRisk">
              New Assessment
            </Button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import {
  ArrowPathIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ShieldExclamationIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  BellIcon,
  AcademicCapIcon,
  MagnifyingGlassIcon
} from '@heroicons/vue/24/outline'
import Button from '@/components/ui/Button.vue'

const router = useRouter()

// Reactive data
const isLoading = ref(false)
const isLiveUpdates = ref(true)
const activeFilter = ref('All')

// KPI Data
const kpiData = ref([
  {
    id: 'total-risks',
    label: 'Total Risks',
    value: '47',
    change: '+5 this month',
    changeType: 'positive',
    trend: 'up',
    icon: ShieldExclamationIcon,
    iconColor: 'text-red-500'
  },
  {
    id: 'bcp-plans',
    label: 'BCP Plans',
    value: '23',
    change: '+2 updated',
    changeType: 'positive',
    trend: 'up',
    icon: DocumentTextIcon,
    iconColor: 'text-blue-500'
  },
  {
    id: 'incidents',
    label: 'Open Incidents',
    value: '3',
    change: '-1 resolved',
    changeType: 'positive',
    trend: 'down',
    icon: ExclamationTriangleIcon,
    iconColor: 'text-yellow-500'
  },
  {
    id: 'compliance',
    label: 'Compliance Score',
    value: '94%',
    change: '+2% improved',
    changeType: 'positive',
    trend: 'up',
    icon: BellIcon,
    iconColor: 'text-green-500'
  }
])

// Health Status
const healthStatus = ref({
  percentage: 94,
  level: 'healthy',
  label: 'Healthy',
  description: 'All systems are operating normally'
})

const healthDetails = ref([
  { name: 'API Services', status: 'healthy', value: '99.9%' },
  { name: 'Database', status: 'healthy', value: '100%' },
  { name: 'Background Jobs', status: 'healthy', value: '98.5%' },
  { name: 'External Integrations', status: 'healthy', value: '97.2%' }
])

// Quick Actions
const quickActions = ref([
  {
    id: 'create-risk',
    title: 'New Risk Assessment',
    description: 'Start a new risk assessment',
    icon: ShieldExclamationIcon
  },
  {
    id: 'update-bcp',
    title: 'Update BCP',
    description: 'Review and update business continuity plans',
    icon: DocumentTextIcon
  },
  {
    id: 'schedule-training',
    title: 'Schedule Training',
    description: 'Plan new training sessions',
    icon: AcademicCapIcon
  },
  {
    id: 'run-audit',
    title: 'Run Audit',
    description: 'Initiate compliance audit',
    icon: MagnifyingGlassIcon
  }
])

// Activity Data
const activityFilters = ['All', 'Risk', 'BCP', 'Incidents', 'Training', 'Audit']

const activities = ref([
  {
    id: 1,
    type: 'risk',
    title: 'High-risk vulnerability identified',
    description: 'Critical security vulnerability found in payment processing system',
    severity: 'high',
    user: 'John Smith',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    module: 'Risk Management',
    icon: ShieldExclamationIcon
  },
  {
    id: 2,
    type: 'bcp',
    title: 'BCP plan updated',
    description: 'Emergency response plan for data center outage has been revised',
    severity: 'medium',
    user: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    module: 'BCP Management',
    icon: DocumentTextIcon
  }
])

// Risk Data
const riskData = ref({
  high: 12,
  medium: 23,
  low: 12
})

// Computed
const filteredActivities = computed(() => {
  if (activeFilter.value === 'All') {
    return activities.value
  }
  return activities.value.filter(activity =>
    activity.type.toLowerCase() === activeFilter.value.toLowerCase()
  )
})

// Methods
const refresh = async () => {
  isLoading.value = true
  // Simulate API call
  await new Promise(resolve => setTimeout(resolve, 1000))
  isLoading.value = false
}

const executeAction = (actionId: string) => {
  switch (actionId) {
    case 'create-risk':
      router.push('/risk-assessment')
      break
    case 'update-bcp':
      router.push('/bcp-development')
      break
    case 'schedule-training':
      router.push('/training-management')
      break
    case 'run-audit':
      router.push('/audit-management')
      break
  }
}

const viewActivity = (activityId: number) => {
  console.log('View activity:', activityId)
}

const viewRisks = () => {
  router.push('/risk-assessment')
}

const createRisk = () => {
  router.push('/risk-assessment/new')
}

const formatTime = (timestamp: Date) => {
  const now = new Date()
  const diff = now.getTime() - timestamp.getTime()
  const minutes = Math.floor(diff / (1000 * 60))

  if (minutes < 60) {
    return `${minutes}m ago`
  }

  const hours = Math.floor(minutes / 60)
  if (hours < 24) {
    return `${hours}h ago`
  }

  const days = Math.floor(hours / 24)
  return `${days}d ago`
}

onMounted(() => {
  // Initialize dashboard
  refresh()
})
</script>

<style lang="scss" scoped>
.dashboard {
  @apply p-6 min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800;
}

.dashboard-header {
  @apply flex items-center justify-between mb-8;
}

.dashboard-title {
  @apply text-3xl font-bold text-slate-900 dark:text-white;
}

.dashboard-subtitle {
  @apply text-slate-600 dark:text-slate-400 mt-1;
}

.header-actions {
  @apply flex gap-3;
}

.refresh-button {
  @apply flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors disabled:opacity-50;
}

.kpi-grid {
  @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8;
}

.kpi-card {
  @apply bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700;
}

.kpi-header {
  @apply flex items-center justify-between mb-4;
}

.kpi-icon {
  @apply w-8 h-8;
}

.kpi-trend {
  @apply flex items-center justify-center w-6 h-6 rounded-full;

  &.up {
    @apply bg-green-100 text-green-600 dark:bg-green-900/50 dark:text-green-400;
  }

  &.down {
    @apply bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400;
  }
}

.kpi-value {
  @apply text-2xl font-bold text-slate-900 dark:text-white mb-1;
}

.kpi-label {
  @apply text-sm text-slate-600 dark:text-slate-400 mb-2;
}

.kpi-change {
  @apply text-xs font-medium;

  &.positive {
    @apply text-green-600 dark:text-green-400;
  }

  &.negative {
    @apply text-red-600 dark:text-red-400;
  }
}

.content-grid {
  @apply grid grid-cols-1 lg:grid-cols-2 gap-6;
}

.dashboard-card {
  @apply bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700;
}

.card-header {
  @apply flex items-center justify-between mb-6;
}

.card-title {
  @apply text-lg font-semibold text-slate-900 dark:text-white;
}

.health-status {
  @apply px-3 py-1 text-sm font-medium rounded-full;

  &.healthy {
    @apply bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300;
  }

  &.warning {
    @apply bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300;
  }

  &.critical {
    @apply bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300;
  }
}

.health-overview {
  @apply flex justify-center mb-6;
}

.health-circle {
  @apply w-24 h-24 rounded-full flex items-center justify-center text-center border-4 transition-all;

  &.healthy {
    @apply border-green-500 bg-green-50 dark:bg-green-900/20;
  }

  &.warning {
    @apply border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20;
  }

  &.critical {
    @apply border-red-500 bg-red-50 dark:bg-red-900/20;
  }
}

.health-percentage {
  @apply text-xl font-bold text-slate-900 dark:text-white;
}

.health-status-text {
  @apply text-center text-sm text-slate-600 dark:text-slate-400 mt-2;
}

.health-details {
  @apply space-y-3;
}

.health-item {
  @apply flex items-center gap-3 justify-between;
}

.health-indicator {
  @apply w-3 h-3 rounded-full bg-red-500 flex-shrink-0;

  &.healthy {
    @apply bg-green-500;
  }
}

.health-value {
  @apply text-sm text-slate-600 dark:text-slate-400;
}

.activity-controls {
  @apply flex items-center justify-between mb-4 pb-3 border-b border-slate-200 dark:border-slate-700;
}

.activity-filters {
  @apply flex gap-2;
}

.filter-button {
  @apply px-3 py-1 text-sm rounded-full border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors;

  &.active {
    @apply bg-blue-100 border-blue-300 text-blue-700 dark:bg-blue-900/50 dark:border-blue-600 dark:text-blue-300;
  }
}

.activity-live-indicator {
  @apply flex items-center gap-2 text-xs font-medium text-slate-500 dark:text-slate-500;

  &.active {
    @apply text-green-600 dark:text-green-400;
  }
}

.live-dot {
  @apply w-2 h-2 rounded-full bg-slate-400 dark:bg-slate-600;

  .activity-live-indicator.active & {
    @apply bg-green-500 animate-pulse;
  }
}

.activity-list {
  @apply space-y-3 max-h-96 overflow-y-auto;
}

.activity-item {
  @apply flex gap-3 p-3 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 cursor-pointer transition-colors;
}

.activity-icon {
  @apply flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center;

  &.activity-risk {
    @apply bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400;
  }

  &.activity-bcp {
    @apply bg-blue-100 text-blue-600 dark:bg-blue-900/50 dark:text-blue-400;
  }

  &.activity-incident {
    @apply bg-yellow-100 text-yellow-600 dark:bg-yellow-900/50 dark:text-yellow-400;
  }

  &.activity-training {
    @apply bg-purple-100 text-purple-600 dark:bg-purple-900/50 dark:text-purple-400;
  }

  &.activity-audit {
    @apply bg-green-100 text-green-600 dark:bg-green-900/50 dark:text-green-400;
  }
}

.activity-content {
  @apply flex-1 min-w-0;
}

.activity-header {
  @apply flex items-start justify-between gap-2 mb-1;
}

.activity-title {
  @apply text-sm font-medium text-slate-900 dark:text-white;
}

.activity-severity {
  @apply px-2 py-0.5 text-xs font-medium rounded-full flex-shrink-0;

  &.high {
    @apply bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300;
  }

  &.medium {
    @apply bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300;
  }

  &.low {
    @apply bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300;
  }
}

.activity-description {
  @apply text-sm text-slate-600 dark:text-slate-400 mb-2;
}

.activity-meta {
  @apply flex items-center gap-3 text-xs text-slate-500 dark:text-slate-500;
}

.activity-user {
  @apply font-medium;
}

.quick-actions-grid {
  @apply grid grid-cols-1 sm:grid-cols-2 gap-4;
}

.quick-action-button {
  @apply p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:shadow-md hover:border-blue-300 dark:hover:border-blue-600 transition-all text-left;
}

.action-icon {
  @apply w-8 h-8 text-blue-600 dark:text-blue-400 mb-2;
}

.action-title {
  @apply block font-semibold text-slate-900 dark:text-white mb-1;
}

.action-description {
  @apply block text-sm text-slate-600 dark:text-slate-400;
}

.risk-container {
  @apply space-y-4;
}

.risk-chart {
  @apply h-48 cursor-pointer;

  canvas {
    @apply w-full h-full;
  }
}

.risk-summary {
  @apply flex justify-around py-3 border-y border-slate-200 dark:border-slate-700;
}

.risk-item {
  @apply flex items-center gap-2 text-sm;
}

.risk-indicator {
  @apply w-3 h-3 rounded-full;

  .risk-item.high & {
    @apply bg-red-500;
  }

  .risk-item.medium & {
    @apply bg-yellow-500;
  }

  .risk-item.low & {
    @apply bg-green-500;
  }
}

.risk-actions {
  @apply flex gap-2;
}

// Responsive adjustments
@media (max-width: 768px) {
  .dashboard {
    @apply p-4;
  }

  .dashboard-header {
    @apply flex-col gap-4;
  }

  .content-grid {
    @apply grid-cols-1;
  }

  .kpi-grid {
    @apply grid-cols-1 sm:grid-cols-2;
  }
}

// Dark mode adjustments
@media (prefers-color-scheme: dark) {
  .dashboard {
    @apply bg-gradient-to-br from-slate-900 to-slate-800;
  }
}

// Print styles
@media print {
  .dashboard {
    @apply bg-white text-black;
  }

  .header-actions,
  .quick-actions-grid,
  .refresh-button {
    @apply hidden;
  }
}
</style>

// interface/interface-materials/interface/web-app/src/app/dashboard/page.tsx
'use client'

import { useQuery } from '@tanstack/react-query'
import { apiClient } from '@/lib/api-client'
import { MainLayout } from '@/components/layout/main-layout'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  FileText,
  Shield,
  TrendingUp,
  Users,
  Zap,
} from 'lucide-react'

export default function DashboardPage() {
  // Fetch dashboard data
  const { data: summary, isLoading } = useQuery({
    queryKey: ['dashboard', 'summary'],
    queryFn: () => apiClient.getDashboardSummary(),
    // Fallback mock data for development
    placeholderData: {
      total_assessments: 12,
      active_risks: 8,
      compliance_score: 87,
      active_incidents: 2,
      critical_processes: 15,
      overdue_tasks: 3,
    },
  })

  if (isLoading) {
    return (
      <MainLayout>
        <div className="flex items-center justify-center h-full">
          <div className="text-center">
            <Activity className="h-12 w-12 animate-spin mx-auto text-primary" />
            <p className="mt-4 text-muted-foreground">Loading dashboard...</p>
          </div>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-muted-foreground">
            Welcome to your Business Continuity Management platform
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <StatCard
            title="BIA Assessments"
            value={summary?.total_assessments || 0}
            description="Active assessments"
            icon={FileText}
            trend="+2 this month"
          />
          <StatCard
            title="Active Risks"
            value={summary?.active_risks || 0}
            description="Requires attention"
            icon={AlertTriangle}
            trend="3 high priority"
            variant="warning"
          />
          <StatCard
            title="ISO 22301 Compliance"
            value={`${summary?.compliance_score || 0}%`}
            description="Overall compliance"
            icon={Shield}
            trend="+5% from last audit"
            variant="success"
          />
          <StatCard
            title="Critical Processes"
            value={summary?.critical_processes || 0}
            description="Monitored processes"
            icon={Activity}
            trend="All systems operational"
          />
        </div>

        {/* Main Content Grid */}
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Journey Timeline */}
          <Card>
            <CardHeader>
              <CardTitle>BCM Journey</CardTitle>
              <CardDescription>Your progress toward full compliance</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <JourneyStep
                title="Organization Setup"
                status="completed"
                description="Profile and configuration complete"
              />
              <JourneyStep
                title="Business Impact Analysis"
                status="in-progress"
                description="12 assessments, 3 in progress"
                progress={75}
              />
              <JourneyStep
                title="Risk Assessment"
                status="in-progress"
                description="8 risks identified and assessed"
                progress={60}
              />
              <JourneyStep
                title="Recovery Planning"
                status="pending"
                description="Not started"
              />
              <JourneyStep
                title="Testing & Exercises"
                status="pending"
                description="Not started"
              />
            </CardContent>
          </Card>

          {/* AI Recommendations */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Zap className="h-5 w-5 text-yellow-500" />
                AI Recommendations
              </CardTitle>
              <CardDescription>Intelligent insights from your data</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <RecommendationItem
                priority="high"
                title="Critical Process Missing RTO"
                description="Payment Processing system lacks defined Recovery Time Objective"
                action="Define RTO"
              />
              <RecommendationItem
                priority="medium"
                title="Risk Treatment Overdue"
                description="3 high-priority risks have passed treatment deadline"
                action="Review Risks"
              />
              <RecommendationItem
                priority="low"
                title="Documentation Update"
                description="Business Continuity Policy requires annual review"
                action="Review Policy"
              />
            </CardContent>
          </Card>
        </div>

        {/* Recent Activities & Risk Overview */}
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Recent Activities */}
          <Card>
            <CardHeader>
              <CardTitle>Recent Activities</CardTitle>
              <CardDescription>Latest updates across the platform</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <ActivityItem
                type="bia"
                title="BIA Assessment Completed"
                description="IT Infrastructure - Criticality: High"
                time="2 hours ago"
                user="John Smith"
              />
              <ActivityItem
                type="risk"
                title="Risk Assessed"
                description="Cybersecurity Threat - Score: 15/25"
                time="5 hours ago"
                user="Sarah Johnson"
              />
              <ActivityItem
                type="document"
                title="Document Approved"
                description="Incident Response Plan v2.1"
                time="1 day ago"
                user="Admin"
              />
              <ActivityItem
                type="compliance"
                title="Gap Analysis Updated"
                description="ISO 22301:2019 - 5 new items"
                time="2 days ago"
                user="Mike Davis"
              />
            </CardContent>
          </Card>

          {/* Risk Heat Map Preview */}
          <Card>
            <CardHeader>
              <CardTitle>Risk Overview</CardTitle>
              <CardDescription>Distribution by severity</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <RiskBar label="Critical" count={2} total={20} color="bg-red-500" />
                <RiskBar label="High" count={6} total={20} color="bg-orange-500" />
                <RiskBar label="Medium" count={8} total={20} color="bg-yellow-500" />
                <RiskBar label="Low" count={4} total={20} color="bg-green-500" />
              </div>
              <div className="mt-4 pt-4 border-t">
                <p className="text-sm text-muted-foreground">
                  Total: <span className="font-semibold">{summary?.active_risks || 0} active risks</span>
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Quick Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
            <CardDescription>Common tasks and workflows</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-3">
              <QuickActionButton
                icon={FileText}
                title="New BIA Assessment"
                description="Start business impact analysis"
              />
              <QuickActionButton
                icon={AlertTriangle}
                title="Report Risk"
                description="Identify and assess new risk"
              />
              <QuickActionButton
                icon={Activity}
                title="Run Simulation"
                description="Digital Twin disruption test"
              />
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  )
}

// Component Helpers
function StatCard({
  title,
  value,
  description,
  icon: Icon,
  trend,
  variant = 'default',
}: any) {
  const colors = {
    default: 'bg-blue-500',
    warning: 'bg-yellow-500',
    success: 'bg-green-500',
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
        <Icon className={`h-4 w-4 ${colors[variant]} text-white rounded p-0.5`} />
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{value}</div>
        <p className="text-xs text-muted-foreground">{description}</p>
        {trend && (
          <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1">
            <TrendingUp className="h-3 w-3" />
            {trend}
          </p>
        )}
      </CardContent>
    </Card>
  )
}

function JourneyStep({ title, status, description, progress }: any) {
  const statusColors = {
    completed: 'bg-green-500',
    'in-progress': 'bg-blue-500',
    pending: 'bg-gray-300',
  }

  return (
    <div className="flex gap-4">
      <div className="flex flex-col items-center">
        <div
          className={`h-8 w-8 rounded-full ${statusColors[status]} flex items-center justify-center`}
        >
          {status === 'completed' && <CheckCircle2 className="h-5 w-5 text-white" />}
          {status === 'in-progress' && <Activity className="h-5 w-5 text-white animate-pulse" />}
        </div>
        {status !== 'pending' && <div className="w-0.5 h-full bg-gray-200 mt-2" />}
      </div>
      <div className="flex-1 pb-4">
        <h4 className="font-semibold">{title}</h4>
        <p className="text-sm text-muted-foreground">{description}</p>
        {progress && (
          <Progress value={progress} className="mt-2 h-2" />
        )}
      </div>
    </div>
  )
}

function RecommendationItem({ priority, title, description, action }: any) {
  const priorityColors = {
    high: 'destructive',
    medium: 'warning',
    low: 'secondary',
  }

  return (
    <div className="flex items-start gap-3 p-3 border rounded-lg">
      <Zap className="h-5 w-5 text-yellow-500 mt-0.5" />
      <div className="flex-1">
        <div className="flex items-center gap-2">
          <h4 className="font-semibold text-sm">{title}</h4>
          <Badge variant={priorityColors[priority]} className="text-xs">
            {priority}
          </Badge>
        </div>
        <p className="text-sm text-muted-foreground mt-1">{description}</p>
        <button className="text-sm text-primary hover:underline mt-2">
          {action} →
        </button>
      </div>
    </div>
  )
}

function ActivityItem({ type, title, description, time, user }: any) {
  const icons = {
    bia: FileText,
    risk: AlertTriangle,
    document: FileText,
    compliance: Shield,
  }
  const Icon = icons[type]

  return (
    <div className="flex gap-3">
      <div className="h-8 w-8 rounded-full bg-muted flex items-center justify-center">
        <Icon className="h-4 w-4" />
      </div>
      <div className="flex-1">
        <h4 className="text-sm font-semibold">{title}</h4>
        <p className="text-sm text-muted-foreground">{description}</p>
        <p className="text-xs text-muted-foreground mt-1">
          {time} • {user}
        </p>
      </div>
    </div>
  )
}

function RiskBar({ label, count, total, color }: any) {
  const percentage = (count / total) * 100

  return (
    <div>
      <div className="flex justify-between text-sm mb-1">
        <span className="font-medium">{label}</span>
        <span className="text-muted-foreground">{count}</span>
      </div>
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div
          className={`h-full ${color}`}
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  )
}

function QuickActionButton({ icon: Icon, title, description }: any) {
  return (
    <button className="flex items-start gap-3 p-4 border rounded-lg hover:border-primary hover:shadow-md transition-all text-left">
      <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
        <Icon className="h-5 w-5 text-primary" />
      </div>
      <div>
        <h4 className="font-semibold text-sm">{title}</h4>
        <p className="text-xs text-muted-foreground mt-1">{description}</p>
      </div>
    </button>
  )
}
