// maybe_need/и/web_portal_enhanced/src/components/layout/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-content">
      <!-- Left Section -->
      <div class="footer-left">
        <p class="copyright">
          © {{ currentYear }} BCM Platform v2. All rights reserved.
        </p>
      </div>

      <!-- Center Section -->
      <div class="footer-center hidden md:flex">
        <nav class="footer-nav">
          <a href="/docs" class="footer-link">Documentation</a>
          <a href="/support" class="footer-link">Support</a>
          <a href="/privacy" class="footer-link">Privacy</a>
          <a href="/terms" class="footer-link">Terms</a>
        </nav>
      </div>

      <!-- Right Section -->
      <div class="footer-right">
        <div class="version-info">
          <span class="version-label">Version:</span>
          <span class="version-number">{{ version }}</span>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { computed } from 'vue'

// Computed
const currentYear = computed(() => new Date().getFullYear())
const version = computed(() => import.meta.env.VITE_APP_VERSION || '2.0.0')
</script>

<style lang="scss" scoped>
.footer {
  @apply bg-white dark:bg-gray-800 px-4 sm:px-6 lg:px-8 py-4;
}

.footer-content {
  @apply flex items-center justify-between;
}

.footer-left {
  @apply flex items-center;
}

.copyright {
  @apply text-sm text-gray-500 dark:text-gray-400;
}

.footer-center {
  @apply flex items-center;
}

.footer-nav {
  @apply flex items-center space-x-6;
}

.footer-link {
  @apply text-sm text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200
         transition-colors duration-200;
}

.footer-right {
  @apply flex items-center;
}

.version-info {
  @apply flex items-center space-x-2 text-sm;
}

.version-label {
  @apply text-gray-500 dark:text-gray-400;
}

.version-number {
  @apply font-mono text-gray-700 dark:text-gray-300;
}
</style>

// можетпригодится/ COGNITIVE ORCHESTRATION-ISO22301/BCM-v1/frontend/bcm-marketplace/src/components/layout/Footer.tsx
import React from 'react'
import Link from 'next/link'

export function Footer() {
  return (
    <footer className="bg-gray-900 text-white">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Company Info */}
          <div className="col-span-1">
            <div className="flex items-center space-x-2 mb-4">
              <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">BCM</span>
              </div>
              <span className="text-xl font-bold">Marketplace</span>
            </div>
            <p className="text-gray-400 text-sm mb-4">
              Global marketplace for Business Continuity Management professionals.
            </p>
            <div className="flex space-x-4">
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <span className="sr-only">Facebook</span>
                {/* Facebook icon */}
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <span className="sr-only">LinkedIn</span>
                {/* LinkedIn icon */}
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                <span className="sr-only">Twitter</span>
                {/* Twitter icon */}
              </a>
            </div>
          </div>

          {/* For Clients */}
          <div className="col-span-1">
            <h3 className="text-lg font-semibold mb-4">For Clients</h3>
            <ul className="space-y-2">
              <li>
                <Link href="/specialists" className="text-gray-400 hover:text-white transition-colors">
                  Find Specialists
                </Link>
              </li>
              <li>
                <Link href="/client/create-request" className="text-gray-400 hover:text-white transition-colors">
                  Post Project
                </Link>
              </li>
              <li>
                <Link href="/how-it-works" className="text-gray-400 hover:text-white transition-colors">
                  How it Works
                </Link>
              </li>
            </ul>
          </div>

          {/* For Specialists */}
          <div className="col-span-1">
            <h3 className="text-lg font-semibold mb-4">For Specialists</h3>
            <ul className="space-y-2">
              <li>
                <Link href="/specialist/register" className="text-gray-400 hover:text-white transition-colors">
                  Join as Expert
                </Link>
              </li>
              <li>
                <Link href="/requests" className="text-gray-400 hover:text-white transition-colors">
                  Browse Projects
                </Link>
              </li>
              <li>
                <Link href="/community" className="text-gray-400 hover:text-white transition-colors">
                  Community
                </Link>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div className="col-span-1">
            <h3 className="text-lg font-semibold mb-4">Support</h3>
            <ul className="space-y-2">
              <li>
                <Link href="/help" className="text-gray-400 hover:text-white transition-colors">
                  Help Center
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-gray-400 hover:text-white transition-colors">
                  Contact Us
                </Link>
              </li>
              <li>
                <Link href="/privacy" className="text-gray-400 hover:text-white transition-colors">
                  Privacy Policy
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="border-t border-gray-800 mt-8 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <p className="text-gray-400 text-sm">
              © 2025 BCM Marketplace. All rights reserved.
            </p>
            <div className="flex space-x-6 mt-4 md:mt-0">
              <Link href="/privacy" className="text-gray-400 hover:text-white text-sm transition-colors">
                Privacy
              </Link>
              <Link href="/terms" className="text-gray-400 hover:text-white text-sm transition-colors">
                Terms
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
